version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
        # 192.168.99.100
      # KAFKA_ADVERTISED_LISTENERS: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
      # Kafka topics
      KAFKA_CREATE_TOPICS: "TestTopic:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
